info:
  description: On Oct-11-2022, the Rabby Swap suffered an exploit with a loss of ~$200,000. There is an external call to RabbyRouter's _swap function, resulting anyone can call this function and transfer out usersâ€™ funds who have approved this contract.
  license: 'UNLICENSED'
  author: 'finn79426'
  references:
    - 'https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/RabbyWallet_SwapRouter.exp.sol'
    - 'https://twitter.com/Supremacy_CA/status/1579813933669486592'
    - https://twitter.com/SlowMist_Team/status/1579839744128978945
    - https://twitter.com/BeosinAlert/status/1579856733178331139
  tags: 
    chains: ['eth']
    project: ['exchange platform']  
    vulnerabilities: [] #wip: CWE here
    exploits: []  
development_framework:
  script: ''
  framework: 'foundry'
networks:
  block_number: '15724451'
  is_forking: '1'
  private_key: ''
  solidity_version: 0.8.10
interfaces:
address:
options: